# Alexa Prompts Language Constants

SKILL_NAME = "SKILL_NAME"
WELCOME_BACK_MESSAGE = "WELCOME_BACK_MESSAGE"
WELCOME_BACK_GYMNASIUM_MESSAGE = "WELCOME_BACK_GYMNASIUM_MESSAGE"
WELCOME_BACK_REALSCHULE_MESSAGE = "WELCOME_BACK_REALSCHULE_MESSAGE"
WELCOME_BACK_MITTELSCHULE_MESSAGE = "WELCOME_BACK_MITTELSCHULE_MESSAGE"
WELCOME_BACK_CLASS_MESSAGE = "WELCOME_BACK_CLASS_MESSAGE"
WELCOME_BACK_LANGUAGE_MESSAGE = "WELCOME_BACK_LANGUAGE_MESSAGE"
WELCOME_BACK_WORDSCHATZ_MESSAGE = "WELCOME_BACK_WORDSCHATZ_MESSAGE"
WELCOME_BACK_UNIT_MESSAGE = "WELCOME_BACK_UNIT_MESSAGE"

GET_LANGUAGE_MESSAGE = "GET_LANGUAGE_MESSAGE"

WELCOME_MESSAGE = "WELCOME_MESSAGE"
GET_GYMNASIUM_MESSAGE = "GET_GYMNASIUM_MESSAGE"
GET_REALSCHULE_MESSAGE = "GET_REALSCHULE_MESSAGE"
GET_MITTELSCHULE_MESSAGE = "GET_MITTELSCHULE_MESSAGE"
GET_SCHOOL_MESSAGE = "GET_SCHOOL_MESSAGE"
GET_CLASS_MESSAGE = "GET_CLASS_MESSAGE"
GET_WORDSCHATZ_MESSAGE = "GET_WORDSCHATZ_MESSAGE"
GET_UNIT_MESSAGE = "GET_UNIT_MESSAGE"
GET_CHAPTER_MESSAGE = "GET_CHAPTER_MESSAGE"
GET_LANGUAGE_MESSAGE = "GET_LANGUAGE_MESSAGE"
GET_LANGUAGE_GYMNASIUM_MESSAGE = "GET_LANGUAGE_GYMNASIUM_MESSAGE"
GET_LANGUAGE_REALSCHULE_MESSAGE = "GET_LANGUAGE_REALSCHULE_MESSAGE"
GET_LANGUAGE_MITTELSCHULE_MESSAGE = "GET_LANGUAGE_MITTELSCHULE_MESSAGE"


REQUEST_CONTINUE_NO_GYM_MESSAGE = "REQUEST_CONTINUE_NO_GYM_MESSAGE"
REQUEST_CONTINUE_GYM_MESSAGE = "REQUEST_CONTINUE_GYM_MESSAGE"

REPROMT_NAME_MESSAGE = "REPROMPT_NAME_MESSAGE"
REPROMPT_SCHOOL_MESSAGE = "REPROMPT_SCHOOL_MESSAGE"
REPROMPT_LANGUAGE_MESSAGE = "REPROMPT_LANGUAGE_MESSAGE"

START_ENGLISCH_SESSION = "START_ENGLISCH_SESSION"
ASK_ENGLISCH_WORD = "ASK_ENGLISCH_WORD"

NO_DATA_MESSAGE = "NO_DATA_MESSAGE"
HELP_MESSAGE = "HELP_MESSAGE"
HELP_REPROMPT = "HELP_REPROMPT"
FALLBACK_MESSAGE = "FALLBACK_MESSAGE"
FALLBACK_REPROMPT = "FALLBACK_REPROMPT"
ERROR_MESSAGE = "ERROR_MESSAGE"
STOP_MESSAGE = "STOP_MESSAGE"
FACTS = "FACTS"